# LSTM+normalization (내 생각과 더해서 하니 수익률 매우높아졌다)

In [219]:
import math
import random

def generate_data(num_trials):
    trials = []
    for _ in range(num_trials):
        count = 0
        while True:
            count += 1
            if random.randint(1, 125) == 1:
                break
        trials.append(count)
    return trials

x_data = generate_data(1000)

def apply_formula(x):
    y = round(1-math.exp(-x/125),4)
    return y

def generate_y_list(x_list):
    y_list = []
    for x in x_list:
        y = apply_formula(x)
        y_list.append(y)
    return y_list

# Y 데이터 리스트 생성
y_data = generate_y_list(x_data)

print("X 데이터:", x_data)
#print("Y 데이터:", y_data)

X 데이터: [134, 483, 47, 17, 153, 21, 213, 19, 146, 46, 60, 223, 294, 66, 47, 133, 19, 30, 18, 67, 227, 187, 154, 168, 33, 498, 165, 276, 171, 38, 137, 128, 35, 73, 132, 101, 34, 16, 65, 178, 10, 35, 310, 12, 93, 34, 100, 282, 170, 103, 197, 24, 121, 9, 3, 48, 257, 146, 116, 194, 157, 86, 209, 246, 240, 107, 57, 122, 13, 68, 178, 198, 107, 25, 354, 216, 7, 300, 50, 128, 182, 271, 173, 86, 12, 197, 210, 61, 270, 3, 180, 173, 98, 66, 112, 55, 8, 40, 109, 15, 164, 142, 171, 97, 371, 63, 73, 17, 458, 176, 422, 107, 33, 170, 43, 192, 93, 18, 294, 137, 30, 133, 42, 171, 155, 51, 90, 319, 39, 476, 191, 37, 36, 320, 77, 146, 1, 2, 10, 264, 145, 226, 42, 3, 41, 69, 71, 14, 268, 43, 453, 448, 59, 100, 310, 77, 29, 5, 3, 81, 179, 11, 72, 18, 139, 120, 85, 69, 96, 19, 132, 160, 143, 1, 278, 25, 167, 101, 90, 5, 104, 255, 297, 996, 6, 42, 16, 260, 19, 121, 72, 56, 29, 335, 118, 688, 15, 357, 246, 246, 85, 11, 306, 5, 5, 19, 20, 64, 61, 3, 136, 32, 21, 109, 15, 225, 4, 26, 53, 75, 156, 1, 11, 208, 88, 

In [203]:
def assign_numbers_based_on_range(numbers, ranges):
    new_list = []
    for number in numbers:
        assigned = False
        for range_start, range_end, assigned_number in ranges:
            if range_start <= number <= range_end:
                new_list.append(assigned_number)
                assigned = True
                break
        if not assigned:
            new_list.append(ranges[-1][2])  # 범위에 속하지 않는 경우 마지막 숫자를 할당(range의 마지막 요소 세번째 요소)
    return new_list

# 사용 예시
numbers = x_data
ranges = [(1, 51, 1), (51, 101, 2), (101, 151, 3), (151, 201, 4),(201, 251, 5),(251, 301, 6)] # 각 세번째 요소는 할당할 숫자를 의미합니다.
normalization_x_data = assign_numbers_based_on_range(numbers, ranges)
print("normalization_x_data =", normalization_x_data)

normalization_x_data = [6, 1, 1, 2, 6, 1, 1, 1, 3, 1, 1, 3, 3, 4, 3, 2, 2, 1, 4, 4, 6, 3, 5, 1, 1, 6, 6, 2, 2, 1, 6, 2, 2, 5, 2, 6, 1, 1, 6, 1, 1, 2, 2, 3, 1, 2, 4, 6, 4, 6, 1, 4, 1, 6, 2, 6, 4, 5, 1, 3, 2, 1, 1, 3, 6, 6, 2, 6, 1, 4, 1, 2, 6, 4, 2, 5, 1, 1, 1, 2, 6, 5, 5, 1, 2, 2, 1, 2, 2, 3, 1, 1, 1, 1, 6, 1, 6, 1, 3, 3, 4, 1, 1, 3, 2, 6, 3, 4, 3, 4, 2, 1, 5, 4, 6, 1, 2, 1, 5, 1, 1, 6, 4, 1, 1, 1, 3, 1, 3, 1, 1, 4, 2, 3, 6, 1, 6, 4, 1, 1, 1, 3, 1, 3, 3, 1, 6, 4, 3, 1, 2, 1, 3, 3, 1, 1, 2, 1, 6, 3, 2, 6, 5, 5, 3, 2, 3, 2, 1, 6, 1, 2, 4, 4, 2, 1, 5, 1, 3, 5, 2, 1, 6, 4, 1, 5, 1, 4, 6, 3, 1, 6, 5, 2, 2, 5, 1, 1, 6, 6, 2, 4, 1, 2, 2, 2, 1, 5, 6, 6, 1, 2, 5, 6, 3, 3, 1, 2, 6, 6, 6, 3, 4, 3, 1, 1, 1, 1, 4, 1, 1, 5, 2, 2, 1, 2, 2, 2, 1, 6, 4, 2, 3, 4, 1, 2, 3, 6, 3, 3, 4, 6, 6, 3, 6, 3, 2, 3, 1, 2, 1, 4, 1, 2, 6, 4, 1, 1, 2, 2, 1, 2, 3, 1, 1, 3, 2, 3, 1, 2, 5, 2, 2, 3, 2, 2, 4, 6, 1, 1, 3, 2, 1, 1, 2, 1, 1, 3, 1, 3, 6, 2, 2, 1, 1, 1, 1, 3, 1, 6, 6, 6, 5, 1, 2, 3, 2, 2, 4, 6, 1, 1, 1, 2, 2, 6

In [204]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np

# 데이터셋 생성 함수
def create_dataset(numbers, n_steps):
    X, y = [], []
    for i in range(len(numbers)):
        end_ix = i + n_steps
        if end_ix > len(numbers)-1:
            break
        seq_x, seq_y = numbers[i:end_ix], numbers[end_ix] # end_ix는 포함되지 않는다.
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# 숫자 시퀀스 정의
numbers = normalization_x_data
n_steps = 3 # 학습하고싶은 숫자묶음의 크기(발걸음)을 설정합니다. #패딩이용해서 자율적으로 컨드롤할수있도록

# 데이터셋 생성
X, y = create_dataset(numbers, n_steps) #데이터셋 생성 함수 활성화

print(X)
print(y)

[[6 1 1]
 [1 1 2]
 [1 2 6]
 ...
 [6 4 1]
 [4 1 1]
 [1 1 4]]
[2 6 1 1 1 3 1 1 3 3 4 3 2 2 1 4 4 6 3 5 1 1 6 6 2 2 1 6 2 2 5 2 6 1 1 6 1
 1 2 2 3 1 2 4 6 4 6 1 4 1 6 2 6 4 5 1 3 2 1 1 3 6 6 2 6 1 4 1 2 6 4 2 5 1
 1 1 2 6 5 5 1 2 2 1 2 2 3 1 1 1 1 6 1 6 1 3 3 4 1 1 3 2 6 3 4 3 4 2 1 5 4
 6 1 2 1 5 1 1 6 4 1 1 1 3 1 3 1 1 4 2 3 6 1 6 4 1 1 1 3 1 3 3 1 6 4 3 1 2
 1 3 3 1 1 2 1 6 3 2 6 5 5 3 2 3 2 1 6 1 2 4 4 2 1 5 1 3 5 2 1 6 4 1 5 1 4
 6 3 1 6 5 2 2 5 1 1 6 6 2 4 1 2 2 2 1 5 6 6 1 2 5 6 3 3 1 2 6 6 6 3 4 3 1
 1 1 1 4 1 1 5 2 2 1 2 2 2 1 6 4 2 3 4 1 2 3 6 3 3 4 6 6 3 6 3 2 3 1 2 1 4
 1 2 6 4 1 1 2 2 1 2 3 1 1 3 2 3 1 2 5 2 2 3 2 2 4 6 1 1 3 2 1 1 2 1 1 3 1
 3 6 2 2 1 1 1 1 3 1 6 6 6 5 1 2 3 2 2 4 6 1 1 1 2 2 6 3 1 3 2 4 2 6 1 1 6
 6 2 3 3 2 1 1 3 1 1 6 1 3 3 3 2 4 3 2 4 1 1 2 3 2 2 1 1 3 3 4 5 1 6 1 6 4
 3 1 3 6 5 2 1 2 3 3 2 4 2 1 2 3 2 2 3 4 1 1 2 1 2 4 2 1 5 3 1 2 3 2 6 4 1
 2 2 6 1 5 3 3 4 1 3 2 4 5 1 4 3 4 3 1 1 4 3 1 4 2 2 2 1 1 3 4 1 4 2 6 3 2
 3 1 6 1 2 6 1 1 4 1 2 2 1 5 1 6 5 6 2 2

In [205]:
# LSTM 모델 정의
from keras.models import Sequential
from keras.layers import LSTM, Dense
from keras.callbacks import EarlyStopping

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, 1))) # 50은 층에있는 뉴런의 수
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# 모델 훈련을 위해 X를 재구성
X = X.reshape((X.shape[0], X.shape[1], 1))

# 조기 종료 콜백 설정
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# 모델 훈련 (내가 생각했을떄 이것은 같은 상황의 반복이므로 에포크를 높게할수록 잘적중될것이다. 그러나 학습하더라도 램덤떄문에 성능개선에 한계가 있다)
model.fit(X, y, epochs=100, verbose=1, callbacks=[early_stopping])

# ETA는 0인데 loss는 계속 내려가면 진정한 학습은 안일어나는데 데이터셋에대해서는 학습이 일어나고 있다는건가?
# 그것이아니라 ETA가 0인것은 매우짧은 시간안에 학습된다는 시간의 의미였다.

Epoch 1/100
32/32 [==============================] - 1s 1ms/step - loss: 7.9666
Epoch 2/100
32/32 [==============================] - 0s 1ms/step - loss: 4.7876
Epoch 3/100
32/32 [==============================] - 0s 1ms/step - loss: 4.2707
Epoch 4/100
32/32 [==============================] - 0s 1ms/step - loss: 4.0230
Epoch 5/100
32/32 [==============================] - 0s 1ms/step - loss: 3.8422
Epoch 6/100
32/32 [==============================] - 0s 1ms/step - loss: 3.6959
Epoch 7/100
32/32 [==============================] - 0s 1ms/step - loss: 3.6235
Epoch 8/100
32/32 [==============================] - 0s 1ms/step - loss: 3.4342
Epoch 9/100
32/32 [==============================] - 0s 1ms/step - loss: 3.3281
Epoch 10/100
32/32 [==============================] - 0s 1ms/step - loss: 3.2628
Epoch 11/100
32/32 [==============================] - 0s 1ms/step - loss: 3.1948
Epoch 12/100
32/32 [==============================] - 0s 1ms/step - loss: 3.2004
Epoch 13/100
32/32 [=================

In [206]:
'''
def assign_numbers_based_on_range(numbers, ranges):
    new_list = []
    for number in numbers:
        assigned = False
        for range_start, range_end, assigned_number in ranges:
            if range_start <= number <= range_end:
                new_list.append(assigned_number)
                assigned = True
                break
        if not assigned:
            new_list.append(ranges[-1][2])  # 범위에 속하지 않는 경우 마지막 숫자를 할당(range의 마지막 요소 세번째 요소)
    return new_list

# 사용 예시
numbers = [342, 123, 232] # 잘작동하나 실험을 학습한 데이터중 하나로하면 실전에서 잘 적용되는지 모르므로 밖에있는 새로운 데이터로 학습시켜보아야한다.
ranges = [(1, 51, 1), (51, 101, 2), (101, 151, 3), (151, 201, 4),(201, 251, 5),(251, 301, 6)] # 각 세번째 요소는 할당할 숫자를 의미합니다.
normalization_x_input = assign_numbers_based_on_range(numbers, ranges)
print("normalization_x_data =", normalization_x_data)
'''

normalization_x_data = [6, 1, 1, 2, 6, 1, 1, 1, 3, 1, 1, 3, 3, 4, 3, 2, 2, 1, 4, 4, 6, 3, 5, 1, 1, 6, 6, 2, 2, 1, 6, 2, 2, 5, 2, 6, 1, 1, 6, 1, 1, 2, 2, 3, 1, 2, 4, 6, 4, 6, 1, 4, 1, 6, 2, 6, 4, 5, 1, 3, 2, 1, 1, 3, 6, 6, 2, 6, 1, 4, 1, 2, 6, 4, 2, 5, 1, 1, 1, 2, 6, 5, 5, 1, 2, 2, 1, 2, 2, 3, 1, 1, 1, 1, 6, 1, 6, 1, 3, 3, 4, 1, 1, 3, 2, 6, 3, 4, 3, 4, 2, 1, 5, 4, 6, 1, 2, 1, 5, 1, 1, 6, 4, 1, 1, 1, 3, 1, 3, 1, 1, 4, 2, 3, 6, 1, 6, 4, 1, 1, 1, 3, 1, 3, 3, 1, 6, 4, 3, 1, 2, 1, 3, 3, 1, 1, 2, 1, 6, 3, 2, 6, 5, 5, 3, 2, 3, 2, 1, 6, 1, 2, 4, 4, 2, 1, 5, 1, 3, 5, 2, 1, 6, 4, 1, 5, 1, 4, 6, 3, 1, 6, 5, 2, 2, 5, 1, 1, 6, 6, 2, 4, 1, 2, 2, 2, 1, 5, 6, 6, 1, 2, 5, 6, 3, 3, 1, 2, 6, 6, 6, 3, 4, 3, 1, 1, 1, 1, 4, 1, 1, 5, 2, 2, 1, 2, 2, 2, 1, 6, 4, 2, 3, 4, 1, 2, 3, 6, 3, 3, 4, 6, 6, 3, 6, 3, 2, 3, 1, 2, 1, 4, 1, 2, 6, 4, 1, 1, 2, 2, 1, 2, 3, 1, 1, 3, 2, 3, 1, 2, 5, 2, 2, 3, 2, 2, 4, 6, 1, 1, 3, 2, 1, 1, 2, 1, 1, 3, 1, 3, 6, 2, 2, 1, 1, 1, 1, 3, 1, 6, 6, 6, 5, 1, 2, 3, 2, 2, 4, 6, 1, 1, 1, 2, 2, 6

# 위에까지가 모델 한덩이

In [209]:
#이렇게 나눠놓으니 위에 학습한것을 토대로 계속 학습하면 시간 안걸리고 다음숫자 예측할수있다.

# 예측을 위한 새로운 데이터 포인트
x_input = np.array([5, 5, 5]) # 학습된 데이터에 대해서는 잘작동하게는 했었다.
x_input = x_input.reshape((1, n_steps, 1))

# 다음 숫자 예측
yhat = model.predict(x_input, verbose=1) # verbose 설정에따라 학습상황을 아려줍니다.
yhat[0][0]  # 예측된 다음 숫자 출력

1/1 [==============================] - 0s 9ms/step


2.6275303

# 새로운 입력 normalization해주기

In [197]:
'''
def assign_numbers_based_on_range(numbers, ranges):
    new_list = []
    for number in numbers:
        assigned = False
        for range_start, range_end, assigned_number in ranges:
            if range_start <= number <= range_end:
                new_list.append(assigned_number)
                assigned = True
                break
        if not assigned:
            new_list.append(ranges[-1][2])  # 범위에 속하지 않는 경우 마지막 숫자를 할당(range의 마지막 요소 세번째 요소)
    return new_list

# 사용 예시
numbers = [79, 114, 5, 3, 169] # 잘작동하나 실험을 학습한 데이터중 하나로하면 실전에서 잘 적용되는지 모르므로 밖에있는 새로운 데이터로 학습시켜보아야한다.
ranges = [(1, 51, 1), (51, 101, 2), (101, 151, 3), (151, 201, 4),(201, 251, 5),(251, 301, 6)] # 각 세번째 요소는 할당할 숫자를 의미합니다.
normalization_x_input = assign_numbers_based_on_range(numbers, ranges)
print("normalization_x_data =", normalization_x_data)
'''

normalization_x_data = [1, 4, 3, 4, 2, 1, 1, 3, 3, 1, 3, 6, 4, 4, 4, 1, 2, 2, 5, 4, 4, 5, 3, 3, 4, 6, 3, 3, 2, 4, 2, 2, 1, 6, 6, 2, 1, 1, 1, 1, 1, 3, 2, 2, 1, 4, 1, 3, 2, 1, 1, 2, 6, 1, 1, 3, 1, 5, 6, 4, 6, 1, 1, 1, 6, 1, 2, 1, 4, 4, 1, 3, 1, 1, 2, 1, 1, 2, 2, 1, 2, 6, 3, 1, 2, 3, 1, 2, 2, 1, 3, 1, 1, 2, 1, 3, 1, 4, 1, 1, 6, 1, 3, 3, 6, 6, 2, 1, 2, 2, 1, 2, 6, 4, 2, 2, 1, 1, 2, 2, 2, 4, 5, 2, 3, 1, 6, 5, 6, 2, 5, 3, 2, 2, 1, 2, 4, 1, 1, 2, 1, 2, 1, 3, 1, 6, 6, 6, 1, 1, 2, 3, 6, 1, 4, 2, 1, 1, 2, 1, 1, 6, 1, 2, 1, 2, 1, 1, 2, 6, 3, 3, 3, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 5, 2, 1, 2, 1, 1, 2, 1, 1, 6, 2, 1, 1, 4, 6, 6, 5]


In [217]:
def assign_numbers_based_on_range(numbers, ranges):
    new_list = []
    for number in numbers:
        assigned = False
        for range_start, range_end, assigned_number in ranges:
            if range_start <= number <= range_end:
                new_list.append(assigned_number)
                assigned = True
                break
        if not assigned:
            new_list.append(ranges[-1][2])  # 범위에 속하지 않는 경우 마지막 숫자를 할당(range의 마지막 요소 세번째 요소)
    return new_list

numbers = [381, 82, 42] # 잘작동하나 실험을 학습한 데이터중 하나로하면 실전에서 잘 적용되는지 모르므로 밖에있는 새로운 데이터로 학습시켜보아야한다.
ranges = [(1, 51, 1), (51, 101, 2), (101, 151, 3), (151, 201, 4),(201, 251, 5),(251, 301, 6)] # 각 세번째 요소는 할당할 숫자를 의미합니다.
normalization_x_input = assign_numbers_based_on_range(numbers, ranges)

x_input = np.array([normalization_x_input]) # 학습된 데이터에 대해서는 잘작동하게는 했었다.
x_input = x_input.reshape((1, n_steps, 1))

# 다음 숫자 예측
yhat = model.predict(x_input, verbose=1) # verbose 설정에따라 학습상황을 아려줍니다.
yhat[0][0]  # 예측된 다음 숫자 출력

1/1 [==============================] - 0s 8ms/step


3.0480866

In [216]:
# 밖에서의 정답률 한번 보자(이것도 코드로 만들수있으나 내가 한번 직접해보고 코드만들자)
# 정답률 재는거 코드로 만들어야 모델 바꿔가며 학습잘되었는지 빠르게 확인할수있다.
'''
1. o
2. x(램덤 변수라 틱장애 같은놈 있으므로 가끔틀릴수도있다.)
3. o
4. o
5. o
6. o(이정도면 모델 완성도 꽤높다 적중률 혼자 예측할떄보다 굉장히 높다.)
7. x
8. x
9.
'''

'\n1. o\n2. x(램덤 변수라 틱장애 같은놈 있으므로 가끔틀릴수도있다.)\n3. o\n4. o\n5. o\n6. o(이정도면 모델 완성도 꽤높다 적중률 혼자 예측할떄보다 굉장히 높다.)\n7. x\n8. x\n9.\n'