<a href="https://colab.research.google.com/github/JoYongJIn/YongJin-Repository/blob/main/%08PyTorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch

# GPU 사용 가능 여부 확인
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# 텐서 정의
x = torch.tensor([1.0, 2.0, 3.0])

# 텐서를 GPU로 이동
x = x.to(device)

print(x.device) # 결과를 보면 GPU사용 가능 환경인지 알수있다.

cpu


In [ ]:
'''
외부 GPU(eGPU) 사용: Thunderbolt 3 포트를 통해 외부 GPU를 맥북에 연결할 수 있습니다.
이 방법은 추가적인 하드웨어 구매가 필요하며, 모든 맥 모델과 호환되지 않을 수 있습니다.
'''

In [7]:
print(torch.rand(2,3))
print(torch.randint(low=0, high=8, size=(2,3)))

tensor([[0.8327, 0.9465, 0.6365],
        [0.6430, 0.2195, 0.0284]])
tensor([[3, 3, 7],
        [7, 5, 4]])


In [ ]:
x_zeros = torch.zeros_like(x.cuda()) # Error: Found no NVIDIA driver on your system. 때문에 cuda기반 연산이 안된다.

In [11]:
import torch

# 사용할 디바이스 설정
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

# 텐서 x 정의 및 디바이스에 할당
x = torch.tensor([1.0, 2.0, 3.0]).to(device)

# x와 같은 크기의 0으로 채워진 텐서 생성
x_zeros = torch.zeros_like(x)

print(x_zeros)

Using cpu device
tensor([0., 0., 0.])


In [16]:
import numpy as np

a = torch.FloatTensor(np.array([[1,2,3],[4,5,6]]))
print(a.type)
print(a)

b = torch.LongTensor(np.array([[1,2,3],[4,5,6]]))
print(b.type)
print(b)

c = torch.ByteTensor(np.array([[1,2,3],[4,5,6]]))
print(c.type)
print(c)

<built-in method type of Tensor object at 0x79578d4918f0>
tensor([[1., 2., 3.],
        [4., 5., 6.]])
<built-in method type of Tensor object at 0x79578d5df100>
tensor([[1, 2, 3],
        [4, 5, 6]])
<built-in method type of Tensor object at 0x79578d659210>
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.uint8)


In [ ]:
import torch

# 24개 요소를 가진 1차원 텐서 생성
x = torch.arange(24)

# x를 2x2x6 차원으로 재구성
print(x.view(2, 2, 6))

print(x.view(-1,1,12))
'''
-1은 PyTorch가 해당 차원의 크기를 자동으로 계산하도록 지시합니다. 이는 "나머지 모든 요소들을 포함하는 차원 크기를 자동으로 계산해 달라"는 의미입니다.
다시 말해, 텐서의 전체 요소 수를 유지하면서 지정된 다른 차원의 크기에 맞춰 자동으로 크기를 조정합니다.
'''

In [ ]:
import torch

# 24개 요소를 가진 1차원 텐서 생성
x = torch.arange(24)

# x를 2x2x6 차원으로 재구성
print(x.view(2, 2, 6))

x_transposed = x.transpose(0,1) # 텐서의 첫번째 차원과 두번째 차원이 바뀌는것으로 두차원이 없이면 오류가된다.
# view vs reshape

In [9]:
import torch

# 24개 요소를 가진 1차원 텐서 생성
x = torch.arange(24)

# x를 2x2x6 차원으로 재구성
x_reshaped = x.view(2, 2, 6)
print(x_reshaped)

# x_reshaped를 전치
x_transposed = x_reshaped.transpose(0, 1)
print(x_transposed)

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])
tensor([[[ 0,  1,  2,  3,  4,  5],
         [12, 13, 14, 15, 16, 17]],

        [[ 6,  7,  8,  9, 10, 11],
         [18, 19, 20, 21, 22, 23]]])


In [10]:
import torch

# 크기가 1인 차원을 포함하는 텐서 생성
x = torch.zeros(2, 1, 2)  # 크기: 2x1x2(행방향으로 요소두개즉 열의개수이고, 열방향으로 요소 한개 즉 행의개수인것이다.)

print("Original tensor:")
print(x)
print("Shape of the original tensor:", x.shape)

# squeeze()를 사용하여 크기가 1인 차원 제거
y = x.squeeze()

print("\nTensor after squeeze:")
print(y)
print("Shape of the tensor after squeeze:", y.shape)

Original tensor:
tensor([[[0., 0.]],

        [[0., 0.]]])
Shape of the original tensor: torch.Size([2, 1, 2])

Tensor after squeeze:
tensor([[0., 0.],
        [0., 0.]])
Shape of the tensor after squeeze: torch.Size([2, 2])


In [11]:
import torch

# 두 텐서 생성
a = torch.tensor([1, 2, 3, 4, 5])
b = torch.tensor([3, 3, 3, 3, 3])

# 같음 (Equal)
eq = torch.eq(a, b) # a == b
print("Equal (a == b):", eq)

# 크거나 같음 (Greater than or equal)
ge = torch.ge(a, b) # a >= b
print("Greater than or equal (a >= b):", ge)

# 큼 (Greater than)
gt = torch.gt(a, b) # a > b
print("Greater than (a > b):", gt)

# 작거나 같음 (Less than or equal)
le = torch.le(a, b) # a <= b
print("Less than or equal (a <= b):", le)

# 작음 (Less than)
lt = torch.lt(a, b) # a < b
print("Less than (a < b):", lt)

Equal (a == b): tensor([False, False,  True, False, False])
Greater than or equal (a >= b): tensor([False, False,  True,  True,  True])
Greater than (a > b): tensor([False, False, False,  True,  True])
Less than or equal (a <= b): tensor([ True,  True,  True, False, False])
Less than (a < b): tensor([ True,  True, False, False, False])


In [19]:
import torch

# STEP 함수 정의
def STEP(x):
    return x > 0

# AND 게이트 함수 정의
def AND(x, w, b):
    z = torch.dot(x, w) + b
    a = STEP(z)
    return a

# NAND 게이트 함수 정의
def NAND(x, w, b):
    z = torch.dot(x, w) + b
    a = STEP(z)
    return a

# OR 게이트 함수 정의
def OR(x, w, b):
    z = torch.dot(x, w) + b
    a = STEP(z)
    return a

# 각 게이트에 알맞은 w, b 가중치 생성
w_and = torch.Tensor([0.5, 0.5])
b_and = torch.Tensor([-0.7])
w_nand = torch.Tensor([-0.5, -0.5])
b_nand = torch.Tensor([0.7])
w_or = torch.Tensor([0.5, 0.5])  # OR 게이트용 가중치 수정
b_or = torch.Tensor([-0.2])      # OR 게이트용 바이어스 수정

# 입력 텐서를 만들어 결과 확인
X = torch.Tensor([[0,0], [0,1], [1,0], [1,1]])
for x in X:
    print("input :", x.long().tolist())
    print("-AND:", AND(x, w=w_and, b=b_and).item())
    print("-NAND:", NAND(x, w=w_nand, b=b_nand).item())
    print("-OR:", OR(x, w=w_or, b=b_or).item())
    print("--" * 15)

'''
.item()은 PyTorch에서 사용되는 함수로, 주로 단일 요소를 가진 텐서에서 Python의 표준 데이터 타입(예: int, float)으로 값을 추출할 때 사용됩니다.
이 메소드는 하나의 요소를 가진 텐서에서 그 값만을 꺼내고 싶을 때 유용하며, 텐서가 단 하나의 요소만을 포함할 때만 사용할 수 있습니다.
'''

input : [0, 0]
-AND: False
-NAND: True
-OR: False
------------------------------
input : [0, 1]
-AND: False
-NAND: True
-OR: True
------------------------------
input : [1, 0]
-AND: False
-NAND: True
-OR: True
------------------------------
input : [1, 1]
-AND: True
-NAND: False
-OR: True
------------------------------


'\n.item()은 PyTorch에서 사용되는 함수로, 주로 단일 요소를 가진 텐서에서 Python의 표준 데이터 타입(예: int, float)으로 값을 추출할 때 사용됩니다.\n이 메소드는 하나의 요소를 가진 텐서에서 그 값만을 꺼내고 싶을 때 유용하며, 텐서가 단 하나의 요소만을 포함할 때만 사용할 수 있습니다.\n'

In [21]:
# XOR문제 해결을 위한 다중퍼셉트론 개발
def solution(x, **kwargs):
    # 새로운 층
    s1 = NAND(x, w=kwargs['w_nand'], b=kwargs['b_nand'])
    s2 = OR(x, w=kwargs['w_or'], b=kwargs['b_or'])
    # 출력층: s1과 s2를 새로운 입력으로 구성하여 전달
    y = AND(torch.Tensor([s1, s2]), w=kwargs['w_and'], b=kwargs['b_and'])
    return y

# 입력 텐서와 타겟 텐서를 생성
input_data = torch.FloatTensor([[0,0], [1,0], [0,1], [1,1]])
target_data = torch.ByteTensor([0, 1, 1, 0])

# 이전에 사용한 가중치를 dictionary 타입으로 만든다.
kwargs = dict([('w_nand', w_nand), ('b_nand', b_nand), ('w_or', w_or), ('b_or', b_or), ('w_and', w_and), ('b_and', b_and)])

# 테스트
for x, y in zip(input_data, target_data):
    pred = solution(x, **kwargs)
    print("Predict:", pred.item(), "| Target:", y.item())

'''
**kwargs는 Python 프로그래밍 언어에서 함수를 정의할 때 사용되는 문법으로,
키워드 인자(keyword arguments)의 가변적인 수를 받을 수 있게 해줍니다. **kwargs는 "keyword arguments"의 약어로,
함수에 전달되는 키워드 인자들을 딕셔너리 형태로 받습니다.
'''

'''
Python의 zip 함수는 여러 개의 이터러블(iterable, 예: 리스트, 튜플 등)을 인자로 받아,
각 이터러블에서 동일한 인덱스에 있는 요소들을 묶어서 이터레이터(iterator)를 생성합니다.
간단히 말해, 여러 개의 시퀀스를 병렬적으로 순회할 수 있게 해주는 함수입니다.
'''

Predict: False | Target: 0
Predict: True | Target: 1
Predict: True | Target: 1
Predict: False | Target: 0


'\n**kwargs는 Python 프로그래밍 언어에서 함수를 정의할 때 사용되는 문법으로,\n키워드 인자(keyword arguments)의 가변적인 수를 받을 수 있게 해줍니다. **kwargs는 "keyword arguments"의 약어로,\n함수에 전달되는 키워드 인자들을 딕셔너리 형태로 받습니다.\n'

기계학습에서 사용되는 신경망 구조는 인간의 뇌 구조에서 영감을 받았지만, 실제 생물학적 뇌 구조와는 상당히 다릅니다. 초기 인공신경망은 뇌의 신경세포(뉴런)의 연결 방식을 모방하여 설계되었으나, 이는 매우 단순화된 형태였습니다.

주요 차이점:
구조적 단순화: 인공신경망의 뉴런은 생물학적 뉴런에 비해 매우 단순합니다. 인공 뉴런은 주로 입력, 가중치, 활성화 함수, 출력으로 구성되어 있으며, 복잡한 생물학적 과정을 모방하지 않습니다.

학습 메커니즘: 인공신경망은 주로 역전파(Backpropagation) 알고리즘과 경사 하강법(Gradient Descent)을 사용하여 학습합니다. 이는 뇌의 학습 방식과는 다른, 수학적으로 정의된 방법입니다.

처리 방식: 인공신경망은 주로 명확하게 정의된 작업(예: 이미지 분류, 텍스트 번역)에 최적화되어 있습니다. 반면, 인간의 뇌는 다양한 유형의 정보를 동시에 처리하고, 유연하게 새로운 상황에 적응할 수 있습니다.

연결 복잡도: 인간 뇌의 연결은 인공신경망보다 훨씬 복잡하고 동적입니다. 뇌는 수십억 개의 뉴런과 수조 개의 시냅스 연결을 가지고 있으며, 이러한 연결은 지속적으로 변화합니다.

결론:
인공신경망은 생물학적 뇌의 기본적인 아이디어를 차용했지만, 그 설계와 작동 방식은 실제 뇌의 복잡성과 유연성을 완전히 반영하지는 못합니다. 인공신경망의 개발은 주로 수학적, 공학적 접근을 기반으로 하며, 특정한 종류의 계산 문제를 효율적으로 해결하는 데 중점을 둡니다. 따라서, 이러한 네트워크는 생물학적 뇌를 이해하는 데 직접적으로 사용되기보다는, 뇌에서 영감을 받은 별개의 컴퓨팅 모델로 간주됩니다.

그러나 발전함에따라 거의 유사해지고 있는것같습니다.

- 한마디로 정리하자면, 파이토치(PyTorch)는 심층 신경망을 구축하고 훈련시키기 위해 주로 사용되는 라이브러리이며, 이 과정에서 텐서 연산을 효율적으로 수행하기 위해 GPU를 활용할 수 있습니다. 파이토치는 GPU를 이용한 고속 텐서 연산 지원 외에도 자동 미분, 다양한 신경망 구조 및 훈련 알고리즘을 제공하여 딥러닝 연구 및 개발에 널리 사용됩니다.