In [41]:
import math
import random

def generate_data(num_trials):
    trials = []
    for _ in range(num_trials):
        count = 0
        while True:
            count += 1
            if random.randint(1, 125) == 1:
                break
        trials.append(count)
    return trials

x_data = generate_data(300)

def apply_formula(x):
    y = round(1-math.exp(-x/125),4)
    return y

def generate_y_list(x_list):
    y_list = []
    for x in x_list:
        y = apply_formula(x)
        y_list.append(y)
    return y_list

# Y 데이터 리스트 생성
y_data = generate_y_list(x_data)

print("X 데이터:", x_data)
#print("Y 데이터:", y_data)

X 데이터: [361, 130, 86, 157, 111, 90, 368, 54, 309, 195, 932, 156, 98, 203, 103, 12, 96, 143, 212, 8, 56, 8, 137, 1, 101, 171, 374, 62, 315, 408, 121, 247, 108, 150, 248, 67, 286, 19, 2, 268, 89, 49, 32, 69, 285, 29, 68, 49, 136, 63, 3, 16, 236, 520, 20, 66, 7, 70, 96, 162, 117, 92, 5, 53, 84, 159, 22, 47, 243, 18, 29, 40, 83, 173, 773, 28, 136, 6, 161, 516, 76, 105, 113, 90, 67, 1, 46, 69, 67, 14, 2, 18, 21, 349, 1160, 519, 51, 286, 129, 64, 30, 190, 22, 21, 49, 217, 282, 61, 18, 83, 263, 9, 1, 78, 65, 191, 33, 138, 6, 313, 21, 64, 105, 347, 87, 47, 148, 340, 27, 5, 123, 195, 16, 49, 12, 153, 47, 295, 36, 59, 6, 17, 15, 19, 2, 187, 66, 53, 70, 118, 12, 51, 183, 23, 105, 6, 27, 144, 154, 71, 206, 15, 9, 364, 180, 51, 49, 232, 59, 286, 61, 60, 41, 20, 405, 207, 84, 208, 435, 261, 37, 213, 81, 122, 17, 161, 294, 53, 94, 320, 147, 249, 54, 60, 42, 140, 207, 95, 30, 13, 4, 294, 2, 281, 43, 213, 195, 94, 267, 152, 80, 246, 160, 28, 59, 555, 8, 39, 245, 105, 1, 139, 35, 132, 28, 165, 89, 97, 2

In [42]:
def assign_numbers_based_on_range(numbers, ranges):
    new_list = []
    for number in numbers:
        assigned = False
        for range_start, range_end, assigned_number in ranges:
            if range_start <= number <= range_end:
                new_list.append(assigned_number)
                assigned = True
                break
        if not assigned:
            new_list.append(ranges[-1][2])  # 범위에 속하지 않는 경우 마지막 숫자를 할당(range의 마지막 요소 세번째 요소)
    return new_list

# 사용 예시
numbers = x_data
ranges = [(1, 51, 1), (51, 101, 2), (101, 151, 3), (151, 201, 4),(201, 251, 5),(251, 301, 6)] # 각 세번째 요소는 할당할 숫자를 의미합니다.
normalization_x_data = assign_numbers_based_on_range(numbers, ranges)
print("normalization_x_data =", normalization_x_data)

normalization_x_data = [6, 3, 2, 4, 3, 2, 6, 2, 6, 4, 6, 4, 2, 5, 3, 1, 2, 3, 5, 1, 2, 1, 3, 1, 2, 4, 6, 2, 6, 6, 3, 5, 3, 3, 5, 2, 6, 1, 1, 6, 2, 1, 1, 2, 6, 1, 2, 1, 3, 2, 1, 1, 5, 6, 1, 2, 1, 2, 2, 4, 3, 2, 1, 2, 2, 4, 1, 1, 5, 1, 1, 1, 2, 4, 6, 1, 3, 1, 4, 6, 2, 3, 3, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 6, 6, 6, 1, 6, 3, 2, 1, 4, 1, 1, 1, 5, 6, 2, 1, 2, 6, 1, 1, 2, 2, 4, 1, 3, 1, 6, 1, 2, 3, 6, 2, 1, 3, 6, 1, 1, 3, 4, 1, 1, 1, 4, 1, 6, 1, 2, 1, 1, 1, 1, 1, 4, 2, 2, 2, 3, 1, 1, 4, 1, 3, 1, 1, 3, 4, 2, 5, 1, 1, 6, 4, 1, 1, 5, 2, 6, 2, 2, 1, 1, 6, 5, 2, 5, 6, 6, 1, 5, 2, 3, 1, 4, 6, 2, 2, 6, 3, 5, 2, 2, 1, 3, 5, 2, 1, 1, 1, 6, 1, 6, 1, 5, 4, 2, 6, 4, 2, 5, 4, 1, 2, 6, 1, 1, 5, 3, 1, 3, 1, 3, 1, 4, 2, 2, 5, 1, 1, 1, 1, 5, 3, 4, 5, 2, 1, 2, 1, 6, 2, 6, 4, 2, 1, 2, 1, 6, 3, 1, 6, 1, 1, 1, 2, 5, 1, 6, 3, 2, 1, 6, 2, 6, 6, 1, 1, 3, 3, 2, 2, 1, 2, 1, 3, 3, 1, 1, 1, 4, 2, 3, 1, 2, 1, 2, 3, 3, 2, 3, 1, 1, 1, 4, 6, 2, 2, 1]


In [43]:
def slice_list_by_number(input_list, number):
    # 결과를 저장할 리스트 초기화
    result = []
    # 현재 하위 리스트를 저장할 임시 리스트 초기화
    temp_list = []

    # 입력 리스트를 순회하면서 요소를 확인
    for item in input_list:
        # 특정 숫자를 찾으면 현재까지의 리스트를 결과에 추가하고, 임시 리스트를 초기화
        if item == number:
            temp_list.append(item)
            result.append(temp_list)
            temp_list = []
        else:
            # 특정 숫자가 아닌 경우 임시 리스트에 추가
            temp_list.append(item)

    # 남은 요소가 있으면 결과에 추가
    if temp_list:
        result.append(temp_list)

    return result

# 예시 사용
my_list = normalization_x_data
number_to_find = 6
new_normalization_x_data = slice_list_by_number(my_list, number_to_find)
print(new_normalization_x_data)  # 출력: [[1, 2, 3, 4], [5, 4], [6, 7, 4]]

[[6], [3, 2, 4, 3, 2, 6], [2, 6], [4, 6], [4, 2, 5, 3, 1, 2, 3, 5, 1, 2, 1, 3, 1, 2, 4, 6], [2, 6], [6], [3, 5, 3, 3, 5, 2, 6], [1, 1, 6], [2, 1, 1, 2, 6], [1, 2, 1, 3, 2, 1, 1, 5, 6], [1, 2, 1, 2, 2, 4, 3, 2, 1, 2, 2, 4, 1, 1, 5, 1, 1, 1, 2, 4, 6], [1, 3, 1, 4, 6], [2, 3, 3, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 6], [6], [6], [1, 6], [3, 2, 1, 4, 1, 1, 1, 5, 6], [2, 1, 2, 6], [1, 1, 2, 2, 4, 1, 3, 1, 6], [1, 2, 3, 6], [2, 1, 3, 6], [1, 1, 3, 4, 1, 1, 1, 4, 1, 6], [1, 2, 1, 1, 1, 1, 1, 4, 2, 2, 2, 3, 1, 1, 4, 1, 3, 1, 1, 3, 4, 2, 5, 1, 1, 6], [4, 1, 1, 5, 2, 6], [2, 2, 1, 1, 6], [5, 2, 5, 6], [6], [1, 5, 2, 3, 1, 4, 6], [2, 2, 6], [3, 5, 2, 2, 1, 3, 5, 2, 1, 1, 1, 6], [1, 6], [1, 5, 4, 2, 6], [4, 2, 5, 4, 1, 2, 6], [1, 1, 5, 3, 1, 3, 1, 3, 1, 4, 2, 2, 5, 1, 1, 1, 1, 5, 3, 4, 5, 2, 1, 2, 1, 6], [2, 6], [4, 2, 1, 2, 1, 6], [3, 1, 6], [1, 1, 1, 2, 5, 1, 6], [3, 2, 1, 6], [2, 6], [6], [1, 1, 3, 3, 2, 2, 1, 2, 1, 3, 3, 1, 1, 1, 4, 2, 3, 1, 2, 1, 2, 3, 3, 2, 3, 1, 1, 1, 4, 6], [2, 2, 1]]


In [44]:
# 패딩적용하기

from tensorflow.keras.preprocessing.sequence import pad_sequences

# 토큰화된 시퀀스 예시
sequences = new_normalization_x_data

# pad_sequences 함수를 이용한 패딩 적용
# maxlen은 시퀀스의 최대 길이, padding='post'는 뒤쪽으로 패딩 추가
padded_x_data = pad_sequences(sequences, maxlen=30, padding='post')

print(padded_x_data)

[[6 0 0 ... 0 0 0]
 [3 2 4 ... 0 0 0]
 [2 6 0 ... 0 0 0]
 ...
 [6 0 0 ... 0 0 0]
 [1 1 3 ... 1 4 6]
 [2 2 1 ... 0 0 0]]


In [45]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np

# 데이터셋 생성 함수
def create_dataset(numbers_2, n_steps):
    X, y = [], []
    for i in range(len(numbers_2)):
        end_ix = i + n_steps
        if end_ix > len(numbers_2)-1:
            break
        seq_x, seq_y = numbers_2[i:end_ix], numbers_2[end_ix] # end_ix는 포함되지 않는다.
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# 숫자 시퀀스 정의
numbers_2 = padded_x_data
n_steps = 30 # 학습하고싶은 숫자묶음의 크기(발걸음)을 설정합니다. #패딩이용해서 자율적으로 컨드롤할수있도록

# 데이터셋 생성
X, y = create_dataset(numbers_2, n_steps) #데이터셋 생성 함수 활성화

print(X)
print(y)

[[[6 0 0 ... 0 0 0]
  [3 2 4 ... 0 0 0]
  [2 6 0 ... 0 0 0]
  ...
  [6 0 0 ... 0 0 0]
  [1 5 2 ... 0 0 0]
  [2 2 6 ... 0 0 0]]

 [[3 2 4 ... 0 0 0]
  [2 6 0 ... 0 0 0]
  [4 6 0 ... 0 0 0]
  ...
  [1 5 2 ... 0 0 0]
  [2 2 6 ... 0 0 0]
  [3 5 2 ... 0 0 0]]

 [[2 6 0 ... 0 0 0]
  [4 6 0 ... 0 0 0]
  [4 2 5 ... 0 0 0]
  ...
  [2 2 6 ... 0 0 0]
  [3 5 2 ... 0 0 0]
  [1 6 0 ... 0 0 0]]

 ...

 [[1 2 1 ... 0 0 0]
  [1 3 1 ... 0 0 0]
  [2 3 3 ... 0 0 0]
  ...
  [1 1 1 ... 0 0 0]
  [3 2 1 ... 0 0 0]
  [2 6 0 ... 0 0 0]]

 [[1 3 1 ... 0 0 0]
  [2 3 3 ... 0 0 0]
  [6 0 0 ... 0 0 0]
  ...
  [3 2 1 ... 0 0 0]
  [2 6 0 ... 0 0 0]
  [6 0 0 ... 0 0 0]]

 [[2 3 3 ... 0 0 0]
  [6 0 0 ... 0 0 0]
  [6 0 0 ... 0 0 0]
  ...
  [2 6 0 ... 0 0 0]
  [6 0 0 ... 0 0 0]
  [1 1 3 ... 1 4 6]]]
[[3 5 2 2 1 3 5 2 1 1 1 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 5 4 2 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [4 2 5 4 1 2 6 0 0 0 0 0 0 0 0 0 0 0

In [50]:
# LSTM 모델 정의
from keras.models import Sequential
from keras.layers import LSTM, Dense
from keras.callbacks import EarlyStopping

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, 1))) # 50은 층에있는 뉴런의 수
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# 모델 훈련을 위해 X를 재구성
X = X.reshape((X.shape[0], X.shape[1], 1))

# 조기 종료 콜백 설정
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# 모델 훈련 (내가 생각했을떄 이것은 같은 상황의 반복이므로 에포크를 높게할수록 잘적중될것이다. 그러나 학습하더라도 램덤떄문에 성능개선에 한계가 있다)
model.fit(X, y, epochs=500, verbose=1, callbacks=[early_stopping])

# ETA는 0인데 loss는 계속 내려가면 진정한 학습은 안일어나는데 데이터셋에대해서는 학습이 일어나고 있다는건가?
# 그것이아니라 ETA가 0인것은 매우짧은 시간안에 학습된다는 시간의 의미였다.

Epoch 1/5000


ValueError: in user code:

    File "/Users/pc/anaconda3/lib/python3.10/site-packages/keras/src/engine/training.py", line 1377, in train_function  *
        return step_function(self, iterator)
    File "/Users/pc/anaconda3/lib/python3.10/site-packages/keras/src/engine/training.py", line 1360, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/pc/anaconda3/lib/python3.10/site-packages/keras/src/engine/training.py", line 1349, in run_step  **
        outputs = model.train_step(data)
    File "/Users/pc/anaconda3/lib/python3.10/site-packages/keras/src/engine/training.py", line 1126, in train_step
        y_pred = self(x, training=True)
    File "/Users/pc/anaconda3/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/Users/pc/anaconda3/lib/python3.10/site-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'sequential_5' (type Sequential).
    
    Input 0 of layer "lstm_6" is incompatible with the layer: expected shape=(None, None, 1), found shape=(None, 30, 30)
    
    Call arguments received by layer 'sequential_5' (type Sequential):
      • inputs=tf.Tensor(shape=(None, 30, 30), dtype=int32)
      • training=True
      • mask=None


In [24]:
def assign_numbers_based_on_range(numbers_3, ranges):
    new_list = []
    for number_3 in numbers_3:
        assigned = False
        for range_start, range_end, assigned_number in ranges:
            if range_start <= number_3 <= range_end:
                new_list.append(assigned_number)
                assigned = True
                break
        if not assigned:
            new_list.append(ranges[-1][2])  # 범위에 속하지 않는 경우 마지막 숫자를 할당(range의 마지막 요소 세번째 요소)
    return new_list

numbers_3 = [22, 115, 208, 1, 155] # 잘작동하나 실험을 학습한 데이터중 하나로하면 실전에서 잘 적용되는지 모르므로 밖에있는 새로운 데이터로 학습시켜보아야한다.
ranges = [(1, 51, 1), (51, 101, 2), (101, 151, 3), (151, 201, 4),(201, 251, 5),(251, 301, 6)] # 각 세번째 요소는 할당할 숫자를 의미합니다.
normalization_x_input = assign_numbers_based_on_range(numbers_3, ranges)

x_input = np.array([normalization_x_input]) # 학습된 데이터에 대해서는 잘작동하게는 했었다.
x_input = x_input.reshape((1, n_steps, 1))

# 다음 숫자 예측
yhat = model.predict(x_input, verbose=1) # verbose 설정에따라 학습상황을 아려줍니다.
yhat[0][0]  # 예측된 다음 숫자 출력

1/1 [==============================] - 0s 10ms/step


1.8732153