In [4]:
import cv2
img = cv2.imread('chart.jpeg') #해당 경로의 파일 읽어오기
cv2.imshow('img', img) # img 라는 이름의 창에 img를 표시
key = cv2.waitKey(0) # 지정된 시간(ms) 동안 사용자 키 입력 대기
cv2.destroyAllWindows()

In [46]:
import cv2
img = cv2.imread('chart.jpeg')
target_img = img.copy()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # 이진화를 하기전에 그레이스케일로
ret, otsu = cv2.threshold(gray, -1, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

# contours, hierarchy = cv2.findContours(otsu, cv2.RETR_LIST, cv2.CHAIN_APPROX_NONE)
contours, hierarchy = cv2.findContours(otsu, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
print(hierarchy)
print(f'총 발견 개수 : {len(contours)}')

COLOR = (0, 200, 0)
cv2.drawContours(target_img, contours, -1, COLOR, 2)


cv2.imshow('img', img)
cv2.imshow('gray', gray)
cv2.imshow('otsu', otsu)
cv2.imshow('contour', target_img)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[   1   -1   -1   -1]
  [   2    0   -1   -1]
  [   3    1   -1   -1]
  ...
  [1461 1457 1460   -1]
  [  -1   -1   -1 1459]
  [  -1 1459   -1   -1]]]
총 발견 개수 : 1462


주식 차트의 봉의 길이와 꼬리의 길이를 추출하려면 이미지 처리와 컴퓨터 비전 기법을 사용해야 합니다. 이는 일반적으로 이미지에서 각 주식 봉을 찾고, 봉의 높이와 꼬리의 길이를 측정하는 과정을 포함합니다.

Python에서는 OpenCV와 같은 라이브러리를 사용하여 이를 수행할 수 있습니다. 또한 PIL (Python Image Library) 나 Matplotlib와 같은 라이브러리를 사용하여 이미지를 읽고 처리할 수 있습니다.

다음은 가볍게 어떻게 시작할 수 있는지에 대한 개요입니다:

이미지 로드: 먼저 이미지를 로드합니다. 이는 OpenCV의 cv2.imread() 또는 PIL의 Image.open() 함수를 사용하여 수행할 수 있습니다.

이미지 처리: 봉을 추출하기 위해 이미지를 처리해야 합니다. 이는 보통 이진화, 엣지 검출, 세그멘테이션 등의 기법을 포함합니다. OpenCV의 cv2.threshold(), cv2.Canny(), cv2.findContours() 등의 함수를 사용할 수 있습니다.

봉 추출: 이미지 처리 후, 각 봉을 구성하는 픽셀을 추출하고, 봉의 높이와 꼬리의 길이를 계산합니다. 이는 OpenCV의 cv2.boundingRect() 함수를 사용하여 수행할 수 있습니다.

데이터 프레임 생성: 추출된 봉의 높이와 꼬리의 길이 데이터를 사용하여 pandas DataFrame을 생성합니다.

이 프로세스는 이미지의 복잡성, 차트의 형식, 봉의 크기와 배치 등에 따라 크게 달라질 수 있습니다. 이와 같은 작업에는 컴퓨터 비전, 이미지 처리에 대한 이해가 필요하며, 알고리즘은 특정 이미지와 작업에 맞게 조정해야 합니다.

## cv2.findcontours

In [22]:
import cv2
import numpy as np

# 이미지 불러오기
image = cv2.imread('chart.jpeg')

# 이미지를 그레이스케일로 변환
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# 이미지 이진화 - Otsu's thresholding
ret, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

# findContours 함수를 사용해 윤곽선 찾기
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# 모든 윤곽선을 빨간색으로 그리기
cv2.drawContours(image, contours, -1, (0, 200, 0), 2)

# 윤곽선이 그려진 이미지 보기
cv2.imshow('Image with contours', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


## 윤곽선의 세로길이 계산하기(cv2.boundingRect)

In [42]:
import cv2
import numpy as np

# 이미지 읽기
img = cv2.imread('chart.jpeg', cv2.IMREAD_GRAYSCALE)

# 임계값 처리로 이진화 이미지로 변환
_, thresholded = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

# findContours로 윤곽선 찾기
contours, _ = cv2.findContours(thresholded, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# 첫 번째 윤곽선에 대한 바운딩 박스 계산
x, y, w, h = cv2.boundingRect(contours[0])

# 세로 길이 출력
print(f'The vertical length of the first contour is: {h}')

The vertical length of the first contour is: 6


In [43]:
import cv2
import numpy as np

# 이미지 읽기
img = cv2.imread('chart.jpeg', cv2.IMREAD_GRAYSCALE)

# 원본 이미지 복사(윤곽선 그리기 위함)
img_color = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

# 임계값 처리로 이진화 이미지로 변환
_, thresholded = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

# findContours로 윤곽선 찾기
contours, _ = cv2.findContours(thresholded, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# 첫 번째 윤곽선에 대한 바운딩 박스 계산
x, y, w, h = cv2.boundingRect(contours[0])

# 윤곽선 그리기
cv2.drawContours(img_color, contours, 0, (0, 255, 0), 3)  # 첫 번째 윤곽선에 녹색으로 그리기

# 세로 길이 출력
print(f'The vertical length of the first contour is: {h}')

# 첫 번째 윤곽선의 길이(퍼리미터) 계산
contour_length = cv2.arcLength(contours[0], True)  # True는 윤곽선이 닫힌 윤곽선임을 나타냄

print(f'The length of the first contour is: {contour_length}')

# 결과 이미지 보여주기
cv2.imshow('Image with Contour', img_color)
cv2.waitKey(0)
cv2.destroyAllWindows()


The vertical length of the first contour is: 6
The length of the first contour is: 667.6568541526794


In [32]:
import cv2
import numpy as np

# 이미지 읽기
img = cv2.imread('chart.jpeg', cv2.IMREAD_GRAYSCALE)

# 원본 이미지 복사(윤곽선 그리기 위함)
img_color = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

# 임계값 처리로 이진화 이미지로 변환
_, thresholded = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

# findContours로 윤곽선 찾기
contours, _ = cv2.findContours(thresholded, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# 너비가 일정 범위에 속하는 윤곽선 찾기
WIDTH_RANGE = (50, 100)  # 예시로 설정한 너비 범위. 실제 상황에 맞게 조정해야 합니다.
selected_contours = [cnt for cnt in contours if WIDTH_RANGE[0] <= cv2.boundingRect(cnt)[2] <= WIDTH_RANGE[1]]

# 해당하는 윤곽선이 있을 경우
if selected_contours:
    # 첫 번째 윤곽선에 대한 바운딩 박스 계산
    x, y, w, h = cv2.boundingRect(selected_contours[0])

    # 윤곽선 그리기
    cv2.drawContours(img_color, selected_contours, 0, (0, 255, 0), 3)  # 첫 번째 윤곽선에 녹색으로 그리기

    # 세로 길이 출력
    print(f'The vertical length of the first contour is: {h}')

    # 첫 번째 윤곽선의 길이(퍼리미터) 계산
    contour_length = cv2.arcLength(selected_contours[0], True)  # True는 윤곽선이 닫힌 윤곽선임을 나타냄

    print(f'The length of the first contour is: {contour_length}')

    # 결과 이미지 보여주기
    cv2.imshow('Image with Contour', img_color)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

else:
    print('No contour in the specified width range.')


The vertical length of the first contour is: 66
The length of the first contour is: 306.02438521385193


In [48]:
import cv2
import numpy as np

# 이미지 읽기
img = cv2.imread('chart.jpeg', cv2.IMREAD_GRAYSCALE)

# 원본 이미지 복사(윤곽선 그리기 위함)
img_color = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

# 임계값 처리로 이진화 이미지로 변환
_, thresholded = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

# findContours로 윤곽선 찾기
contours, _ = cv2.findContours(thresholded, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

# 너비가 일정 범위에 속하는 윤곽선 찾기
WIDTH_RANGE = (20, 50)
selected_contours = []

# 모든 윤곽선을 검사하며 너비가 WIDTH_RANGE에 해당하는 윤곽선만 selected_contours에 추가
for cnt in contours:
    x, y, w, h = cv2.boundingRect(cnt)
    if WIDTH_RANGE[0] <= w <= WIDTH_RANGE[1]:
        selected_contours.append(cnt)

# selected_contours에 윤곽선이 추가된 경우
if selected_contours:
    # 첫 번째 윤곽선에 대한 바운딩 박스 계산
    x, y, w, h = cv2.boundingRect(selected_contours[0])

    # 모든 윤곽선 그리기
    for i in range(len(selected_contours)):
        cv2.drawContours(img_color, selected_contours, i, (0, 255, 0), 3)

    # 세로 길이 출력
    print(f'The vertical length of the first contour is: {h}')

    # 첫 번째 윤곽선의 길이(퍼리미터) 계산
    contour_length = cv2.arcLength(selected_contours[0], True)  # True는 윤곽선이 닫힌 윤곽선임을 나타냄

    print(f'The length of the first contour is: {contour_length}')

    # 결과 이미지 보여주기
    cv2.imshow('Image with Contour', img_color)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

# WIDTH_RANGE에 해당하는 윤곽선이 없는 경우
else:
    print('No contour in the specified width range.')

The vertical length of the first contour is: 6
The length of the first contour is: 54.24264061450958
