In [39]:
import math
import random

def generate_data(num_trials):
    trials = []
    for _ in range(num_trials):
        count = 0
        while True:
            count += 1
            if random.randint(1, 125) == 1:
                break
        trials.append(count)
    return trials

x_data = generate_data(1000)

def apply_formula(x):
    y = round(1-math.exp(-x/125),4)
    return y

def generate_y_list(x_list):
    y_list = []
    for x in x_list:
        y = apply_formula(x)
        y_list.append(y)
    return y_list

# Y 데이터 리스트 생성
y_data = generate_y_list(x_data)

print("X 데이터:", x_data)
#print("Y 데이터:", y_data)

X 데이터: [115, 56, 1, 4, 76, 164, 85, 105, 132, 60, 101, 36, 175, 3, 23, 20, 245, 233, 20, 29, 68, 47, 7, 212, 111, 27, 17, 112, 204, 51, 76, 43, 75, 109, 106, 76, 457, 491, 542, 69, 264, 233, 81, 306, 25, 96, 35, 231, 317, 20, 202, 171, 160, 9, 272, 17, 10, 211, 113, 41, 94, 11, 1, 71, 33, 41, 33, 159, 16, 1, 548, 10, 83, 20, 20, 47, 32, 40, 26, 56, 314, 113, 110, 71, 8, 22, 171, 108, 88, 66, 169, 339, 28, 39, 11, 104, 17, 297, 137, 46, 58, 135, 179, 22, 225, 78, 320, 196, 484, 30, 38, 347, 15, 183, 110, 39, 12, 215, 194, 118, 12, 146, 399, 52, 283, 146, 16, 19, 37, 276, 37, 233, 124, 48, 234, 114, 63, 138, 131, 141, 40, 15, 349, 117, 109, 72, 101, 117, 113, 172, 115, 18, 3, 647, 43, 27, 44, 26, 144, 34, 124, 96, 232, 3, 36, 200, 46, 91, 136, 148, 18, 18, 243, 11, 7, 27, 42, 316, 153, 121, 5, 114, 133, 47, 13, 401, 11, 110, 405, 31, 100, 153, 1, 82, 260, 275, 264, 48, 283, 50, 43, 396, 325, 46, 31, 65, 148, 34, 51, 358, 78, 133, 68, 32, 61, 125, 592, 139, 59, 264, 17, 139, 369, 3, 42, 3

In [30]:
def assign_numbers_based_on_range(numbers, ranges):
    new_list = []
    for number in numbers:
        assigned = False
        for range_start, range_end, assigned_number in ranges:
            if range_start <= number <= range_end:
                new_list.append(assigned_number)
                assigned = True
                break
        if not assigned:
            new_list.append(ranges[-1][2])  # 범위에 속하지 않는 경우 마지막 숫자를 할당(range의 마지막 요소 세번째 요소)
    return new_list

# 사용 예시
numbers = x_data
ranges = [(1, 111, 1), (111, 201, 2), (201, 301, 3)] # 각 세번째 요소는 할당할 숫자를 의미합니다.
normalization_x_data = assign_numbers_based_on_range(numbers, ranges)
print("normalization_x_data =", normalization_x_data)

normalization_x_data = [2, 2, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 2, 2, 1, 1, 2, 3, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 3, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 2, 3, 1, 3, 3, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 3, 3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2, 2, 1, 3, 3, 1, 1, 3, 1, 1, 3, 3, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 3, 1, 1, 1, 1, 2, 3, 3, 3, 2, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 3, 3, 1, 1, 1, 3, 2, 1, 3, 3, 1, 1, 3, 1, 1, 1, 1, 3, 2, 1, 1, 1, 2, 2, 3, 3, 1, 3, 1, 1, 2, 1, 1, 3, 1, 2, 3, 1, 2, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 3, 3, 2, 3, 1, 1, 3, 1, 3, 2, 2, 2, 1, 3, 1, 3, 1, 3, 1, 1, 1, 3, 1, 3, 3, 2, 2, 3, 1, 2, 1, 1, 1, 2, 3, 2, 1, 1, 2, 2, 1, 2, 3, 2, 3, 1, 3, 1, 1, 1, 1, 1, 1, 3, 2, 3, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 3, 2, 1, 1, 2, 1, 2, 3, 1, 1, 1, 1, 3, 1, 2, 1, 1, 1, 1, 3, 1, 1, 2, 3, 2, 2, 1, 1, 2, 2, 3, 2, 1, 2, 1, 1, 1, 3, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1

In [31]:
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np

# 데이터셋 생성 함수
def create_dataset(numbers, n_steps):
    X, y = [], []
    for i in range(len(numbers)):
        end_ix = i + n_steps
        if end_ix > len(numbers)-1:
            break
        seq_x, seq_y = numbers[i:end_ix], numbers[end_ix] # end_ix는 포함되지 않는다.
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

# 숫자 시퀀스 정의
numbers = normalization_x_data
n_steps = 4 # 학습하고싶은 숫자묶음의 크기(발걸음)을 설정합니다.

# 데이터셋 생성
X, y = create_dataset(numbers, n_steps) #데이터셋 생성 함수 활성화

print(X)
print(y)

[[2 2 3]
 [2 3 1]
 [3 1 1]
 ...
 [3 1 1]
 [1 1 3]
 [1 3 1]]
[1 1 1 ... 3 1 1]


In [33]:
# LSTM 모델 정의
from keras.models import Sequential
from keras.layers import LSTM, Dense
from keras.callbacks import EarlyStopping

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# 모델 훈련을 위해 X를 재구성
X = X.reshape((X.shape[0], X.shape[1], 1))

# 조기 종료 콜백 설정
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

# 모델 훈련 (내가 생각했을떄 이것은 같은 상황의 반복이므로 에포크를 높게할수록 잘적중될것이다. 그러나 학습하더라도 램덤떄문에 성능개선에 한계가 있다)
model.fit(X, y, epochs=20, verbose=1, callbacks=[early_stopping])

Epoch 1/20
625/625 [==============================] - 1s 1ms/step - loss: 0.8410
Epoch 2/20
625/625 [==============================] - 1s 993us/step - loss: 0.6332
Epoch 3/20
625/625 [==============================] - 1s 1ms/step - loss: 0.6333
Epoch 4/20
625/625 [==============================] - 1s 994us/step - loss: 0.6344
Epoch 5/20
625/625 [==============================] - 1s 1ms/step - loss: 0.6332
Epoch 6/20
625/625 [==============================] - 1s 1ms/step - loss: 0.6343
Epoch 7/20
625/625 [==============================] - 1s 1ms/step - loss: 0.6334
Epoch 8/20
625/625 [==============================] - 1s 1ms/step - loss: 0.6332
Epoch 9/20
625/625 [==============================] - 1s 1ms/step - loss: 0.6325
Epoch 10/20
625/625 [==============================] - 1s 990us/step - loss: 0.6326
Epoch 11/20
625/625 [==============================] - 1s 1ms/step - loss: 0.6330
Epoch 12/20
625/625 [==============================] - 1s 1ms/step - loss: 0.6325
Epoch 13/20
625/625

In [38]:
#이렇게 나눠놓으니 위에 학습한것을 토대로 계속 학습하면 시간 안걸리고 다음숫자 예측할수있다.

# 예측을 위한 새로운 데이터 포인트
x_input = np.array([3, 1, 3])
x_input = x_input.reshape((1, n_steps, 1))

# 다음 숫자 예측
yhat = model.predict(x_input, verbose=1) # verbose 설정에따라 학습상황을 아려줍니다.
yhat[0][0]  # 예측된 다음 숫자 출력

1/1 [==============================] - 0s 8ms/step


1.5639086

# 새로운 입력 normalization해주기

In [37]:
def assign_numbers_based_on_range(numbers, ranges):
    new_list = []
    for number in numbers:
        assigned = False
        for range_start, range_end, assigned_number in ranges:
            if range_start <= number <= range_end:
                new_list.append(assigned_number)
                assigned = True
                break
        if not assigned:
            new_list.append(ranges[-1][2])  # 범위에 속하지 않는 경우 마지막 숫자를 할당(range의 마지막 요소 세번째 요소)
    return new_list

# 사용 예시
numbers = [604, 106, 239, 31]
ranges = [(1, 111, 1), (111, 201, 2), (201, 301, 3)] # 각 세번째 요소는 할당할 숫자를 의미합니다.
normalization_x_data = assign_numbers_based_on_range(numbers, ranges)
print("normalization_x_data =", normalization_x_data)

normalization_x_data = [3, 1, 3, 1]
